apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: virtualmachines.aws.compute.starter.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: compute.starter.org/v1alpha1
    kind: VirtualMachine
  resources:
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: Instance
        spec:
          forProvider:
            ami: ami-0d50e5e845c552faf # patched
            instanceType: t2.micro # patched
            region: us-west-1 # patched
      patches:
        - fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
          transforms:
            - type: map
              map:
                east: us-east-1
                west: us-west-1
        - fromFieldPath: spec.parameters.operatingSystem
          toFieldPath: spec.forProvider.ami
          transforms:
            - type: map
              map:
                Windows: ami-00eda368daf738c59 # Windows Server 2022
                Linux (Ubuntu): ami-0d50e5e845c552faf # Ubuntu 22.04 LTS
        - fromFieldPath: spec.parameters.size
          toFieldPath: spec.forProvider.instanceType
          transforms:
            - type: map
              map:
                small: t2.micro
                medium: m4.large
                large: m4.xlarge